import { and, asc, eq, inArray, lte, or } from "drizzle-orm";
import { db, workflowRunsTable, workflowsTable, type Workflow, type WorkflowRun } from "@workspace/db";
export type WorkflowRunClaim = { leaseOwner: string; leaseExpiresAt: Date };
export const createWorkflow = async (values: typeof workflowsTable.$inferInsert): Promise<Workflow> => { const [row] = await db.insert(workflowsTable).values(values).returning(); if (!row) throw new Error("Workflow creation did not return a record"); return row; };
export const getWorkflow = async (id: string): Promise<Workflow | null> => (await db.select().from(workflowsTable).where(eq(workflowsTable.id, id)).limit(1))[0] ?? null;
export const listWorkflows = async (organizationId?: string, workspaceId?: string): Promise<Workflow[]> => { const filters = []; if (organizationId) filters.push(eq(workflowsTable.organizationId, organizationId)); if (workspaceId) filters.push(eq(workflowsTable.workspaceId, workspaceId)); const query = db.select().from(workflowsTable); return (filters.length ? query.where(and(...filters)) : query).orderBy(asc(workflowsTable.createdAt)); };
export const listWorkflowRuns = async (workflowId?: string): Promise<WorkflowRun[]> => { const query = db.select().from(workflowRunsTable); return (workflowId ? query.where(eq(workflowRunsTable.workflowId, workflowId)) : query).orderBy(asc(workflowRunsTable.updatedAt)); };
export const createWorkflowRun = async (values: typeof workflowRunsTable.$inferInsert): Promise<WorkflowRun> => { const [row] = await db.insert(workflowRunsTable).values(values).returning(); if (!row) throw new Error("Workflow run creation did not return a record"); return row; };
export const claimRunnableWorkflowRuns = async (claim: WorkflowRunClaim, limit = 10): Promise<WorkflowRun[]> => { const now = new Date(); const claimable = or(eq(workflowRunsTable.status, "queued"), and(eq(workflowRunsTable.status, "waiting"), lte(workflowRunsTable.nextAttemptAt, now)), and(eq(workflowRunsTable.status, "running"), lte(workflowRunsTable.leaseExpiresAt, now))); const ids = (await db.select({ id: workflowRunsTable.id }).from(workflowRunsTable).where(claimable).orderBy(asc(workflowRunsTable.updatedAt)).limit(limit)).map((x) => x.id); if (!ids.length) return []; return db.update(workflowRunsTable).set({ status: "running", leaseOwner: claim.leaseOwner, leaseExpiresAt: claim.leaseExpiresAt, updatedAt: now }).where(inArray(workflowRunsTable.id, ids)).returning(); };
